### ISSUE TITLE
unknown encoding

### ISSUE THREAD

**Issue by Mr-x2020** [asheykhi/SpeedVpn#1]
what are these files? and how Can I open them for editing?
![image](https://user-images.githubusercontent.com/65666323/182829588-73cdf54c-3e64-4281-a591-75870ba9c23a.png)
![image](https://user-images.githubusercontent.com/65666323/182829772-60c475e2-f406-4f17-9968-1175d9e22fc4.png)

**Comment by asheykhi** [comment]
@Mr-x2020 
x86-64 (also known as x64, x86_64, AMD64, and Intel 64) is a 64-bit version of the x86 instruction set, first released in 1999. It introduced two new modes of operation, 64-bit mode and compatibility mode, along with a new 4-level paging mode.
With 64-bit mode and the new paging mode, it supports vastly larger amounts of virtual memory and physical memory than was possible on its 32-bit predecessors, allowing programs to store larger amounts of data in memory. x86-64 also expands general-purpose registers to 64-bit, and expands the number of them from 8 (some of which had limited or fixed functionality, e.g. for stack management) to 16 (fully general), and provides numerous other enhancements. Floating-point arithmetic is supported via mandatory SSE2-like instructions, and x87/MMX style registers are generally not used (but still available even in 64-bit mode); instead, a set of 16 vector registers, 128 bits each, is used. (Each register can store one or two double-precision numbers or one to four single-precision numbers, or various integer formats.) In 64-bit mode, instructions are modified to support 64-bit operands and 64-bit addressing mode.
* You should not modify this file and just add this file beside other .so shared libraries in asset folder to use by OpenVpn service by CMAKE and NDK.

**Comment by Mr-x2020** [comment]
thank you for your quick reply, I have a couple more question, can we talk in telegram please? here is link https://t.me/+RDgt0LhDMMFlZWE0
