### ISSUE TITLE
ovpn files doesn't show up in android app

### ISSUE THREAD

**Issue by Mr-x2020** [asheykhi/SpeedVpn#3]
I added ovpn files to assets folder but not listed in app

 
![image](https://user-images.githubusercontent.com/65666323/183395492-f9d7bca5-048e-47e9-98db-78b4943ac63b.png)
![image](https://user-images.githubusercontent.com/65666323/183395525-123d426f-a921-43eb-ad53-8d3ee98f065d.png)

why doesn't show up in android app

**Comment by asheykhi** [comment]
Hello dear @Mr-x2020 
In this version just listed provided certs from custom Api not from asset folder . 
You should change adapter of recycler view and get listed .ovpn files from asset folder instead  . 
I'll add asset adapter soon .

**Comment by Mr-x2020** [comment]
HI @asheykhi 
It would be great if This app can update their OVPN files in assets through parsing a json file in remote server like json file in github
![image](https://user-images.githubusercontent.com/65666323/183614152-e2020685-5371-4748-a298-409b1395fc6a.png)

**Comment by asheykhi** [comment]
@Mr-x2020 Ok, Good idea 💡
